# Generated by Django 3.0.2 on 2020-03-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Branches',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branches'),
        ),
        migrations.AlterField(
            model_name='company',
            name='BusinessAreas',
            field=models.TextField(blank=True, null=True, verbose_name='BusinessAreas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='BusinessLicenseNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BusinessLicenseNumber'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CharterCapital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharterCapital'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CompanyName'),
        ),
        migrations.AlterField(
            model_name='company',
            name='DateOfIssue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DateOfIssue'),
        ),
        migrations.AlterField(
            model_name='company',
            name='DateOfListing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DateOfListing'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Employees',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='company',
            name='EstablishmentDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EstablishmentDate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Exchange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ForeignOwnership',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ForeignOwnership'),
        ),
        migrations.AlterField(
            model_name='company',
            name='HeadQuarters',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HeadQuarters'),
        ),
        migrations.AlterField(
            model_name='company',
            name='History',
            field=models.TextField(blank=True, null=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ICBCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ICBCode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='InitialListingPrice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InitialListingPrice'),
        ),
        migrations.AlterField(
            model_name='company',
            name='InternationalName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InternationalName'),
        ),
        migrations.AlterField(
            model_name='company',
            name='IsListed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IsListed'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ListingVolume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ListingVolume'),
        ),
        migrations.AlterField(
            model_name='company',
            name='OtherOwnership',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OtherOwnership'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Overview',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ShortName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ShortName'),
        ),
        migrations.AlterField(
            model_name='company',
            name='StateOwnership',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StateOwnership'),
        ),
        migrations.AlterField(
            model_name='company',
            name='TaxIDNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TaxIDNumber'),
        ),
        migrations.AlterField(
            model_name='company',
            name='WebAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WebAddress'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='Symbol',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Symbol'),
        ),
    ]
