# Generated by Django 3.0.2 on 2020-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200311_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicEPS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicEPS'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicEPSGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicEPSGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicEPSGrowth_LFY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicEPSGrowth_LFY'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicEPSGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicEPSGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicEPSGrowth_MRQ2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicEPSGrowth_MRQ2'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicEPSGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicEPSGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BasicPE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicPE'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='BookValuePerShare',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BookValuePerShare'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='COF',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='COF'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CapitalGainsYield',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CapitalGainsYield'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='Cash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CashDividend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CashDividend'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CharterCapitalGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharterCapitalGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CharterCapitalGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharterCapitalGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CharterCapitalGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharterCapitalGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CostToAssets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CostToAssets'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CostToIncome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CostToIncome'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CostToLoans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CostToLoans'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CurrentAssetsTurnover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CurrentAssetsTurnover'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='CurrentRatio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CurrentRatio'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='Date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedEPS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedEPS'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedEPSGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedEPSGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedEPSGrowth_LFY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedEPSGrowth_LFY'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedEPSGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedEPSGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedEPSGrowth_MRQ2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedEPSGrowth_MRQ2'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedEPSGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedEPSGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DilutedPE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DilutedPE'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DividendInCash_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DividendInCash_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DividendInShares_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DividendInShares_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='DividendYield',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DividendYield'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EBIT',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EBIT'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EBITDA',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EBITDA'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EBITMargin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EBITMargin'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EBITMargin_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EBITMargin_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EPS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EquityGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EquityGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EquityGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EquityGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EquityGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EquityGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='EquityToLoans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EquityToLoans'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='FixedAssets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FixedAssets'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='FreeShares',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FreeShares'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='GrossMargin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GrossMargin'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='GrossMargin_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GrossMargin_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='GrossProfit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GrossProfit'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='InterestCoverageRatio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InterestCoverageRatio'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='InventoryTurnover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InventoryTurnover'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LAR',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LAR'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LDR',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LDR'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LFY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LFY'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LastCashDividendYear',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastCashDividendYear'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LastDividendInCash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastDividendInCash'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LastDividendInCashRecordDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastDividendInCashRecordDate'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LastDividendInShares',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastDividendInShares'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LastDividendInSharesRecordDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastDividendInSharesRecordDate'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LastStockDividendYear',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastStockDividendYear'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LoanlossReservesToLoans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LoanlossReservesToLoans'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LoanlossReservesToNPLs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LoanlossReservesToNPLs'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LoansToDeposit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LoansToDeposit'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='LongtermDebtOverEquity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LongtermDebtOverEquity'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='MarketCapitalization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MarketCapitalization'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NIM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NIM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NPLs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NPLs'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NPLsToLoans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NPLsToLoans'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NetProfitMargin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NetProfitMargin'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NetProfitMargin_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NetProfitMargin_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NetSales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NetSales'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NextDividendInCash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NextDividendInCash'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NextDividendInCashRecordDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NextDividendInCashRecordDate'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NextDividendInShares',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NextDividendInShares'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NextDividendInSharesRecordDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NextDividendInSharesRecordDate'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='NonInterestIncomeToNetInterestIncome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NonInterestIncomeToNetInterestIncome'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='OperatingMargin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OperatingMargin'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='OperatingMargin_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OperatingMargin_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='OtherProfit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OtherProfit'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PB',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PB'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PC',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PC'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PE'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PS'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PT',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PT'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PayoutRatio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayoutRatio'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PreTaxMargin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PreTaxMargin'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PreTaxMargin_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PreTaxMargin_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='PreprovisionROA',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PreprovisionROA'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitAfterIncomeTaxes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitAfterIncomeTaxes'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitBeforeIncomeTaxes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitBeforeIncomeTaxes'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitFromFinancialActivities',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitFromFinancialActivities'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitFromFinancialActivitiesOverProfitBeforeTax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitFromFinancialActivitiesOverProfitBeforeTax'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitGrowth_LFY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitGrowth_LFY'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitGrowth_MRQ2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitGrowth_MRQ2'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProfitGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProfitGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ProvisionChargesToLoans',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProvisionChargesToLoans'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='Quarter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='QuickRatio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QuickRatio'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROA',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROA'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROA_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROA_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROCE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROCE'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROE'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROE_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROE_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROIC',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROIC'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ROIC_03YrAvg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ROIC_03YrAvg'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='ReceivablesTurnover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ReceivablesTurnover'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='RetentionRatio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RetentionRatio'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SalesGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SalesGrowth_LFY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesGrowth_LFY'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SalesGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SalesGrowth_MRQ2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesGrowth_MRQ2'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SalesGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SalesPerShare',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesPerShare'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='SharesOutstanding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SharesOutstanding'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='StockDividend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StockDividend'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='StockHolderEquity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StockHolderEquity'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='StockHolderEquityGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StockHolderEquityGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='StockHolderEquityGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StockHolderEquityGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='StockHolderEquityGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='StockHolderEquityGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='Symbol',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssets'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssetsGrowth_03Yr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssetsGrowth_03Yr'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssetsGrowth_LFY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssetsGrowth_LFY'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssetsGrowth_MRQ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssetsGrowth_MRQ'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssetsGrowth_MRQ2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssetsGrowth_MRQ2'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssetsGrowth_TTM',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssetsGrowth_TTM'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalAssetsTurnover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalAssetsTurnover'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalCurrentAssets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalCurrentAssets'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalDebtOverAssets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalDebtOverAssets'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalDebtOverEquity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalDebtOverEquity'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalInventories',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalInventories'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalLiabilities',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalLiabilities'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalLongTermLiabilities',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalLongTermLiabilities'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalShortTermLiabilities',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalShortTermLiabilities'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='TotalStockReturn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TotalStockReturn'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='YOEA',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='YOEA'),
        ),
        migrations.AlterField(
            model_name='latestfinancialinfo',
            name='Year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Year'),
        ),
    ]
