# Generated by Django 3.0.2 on 2020-03-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20200316_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='historicalquote',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='intradayquote',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='latestfinancialinfo',
            name='is_removed',
        ),
    ]
