# Generated by Django 3.0.2 on 2020-03-17 14:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20200316_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Symbol', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Symbol')),
                ('Exchange', models.CharField(blank=True, max_length=255, verbose_name='Exchange')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
