# Generated by Django 3.0.2 on 2020-03-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_subcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcompany',
            name='Stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_subcompany', to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='Symbol',
            field=models.CharField(blank=True, max_length=255, verbose_name='Symbol'),
        ),
    ]
