# Generated by Django 3.0.2 on 2020-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20200319_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcompany',
            name='CharterCapital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CharterCapital'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CompanyName'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='CompanyProfile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CompanyProfile'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='Exchange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='InstitutionID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InstitutionID'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='InternationalName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InternationalName'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='IsListed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IsListed'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='Ownership',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ownership'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='Shares',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shares'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='ShortName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ShortName'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='Symbol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
