# Generated by Django 3.0.2 on 2020-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20200319_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcompany',
            name='CompanyProfile',
            field=models.TextField(blank=True, null=True, verbose_name='CompanyProfile'),
        ),
        migrations.AlterField(
            model_name='subcompany',
            name='IsListed',
            field=models.BooleanField(default=False, verbose_name='IsListed'),
        ),
    ]
