# Generated by Django 3.0.2 on 2020-03-19 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20200319_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('OfficerID', models.CharField(blank=True, max_length=255, verbose_name='OfficerID')),
                ('IndividualID', models.CharField(blank=True, max_length=255, verbose_name='IndividualID')),
                ('Name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('PositionID', models.CharField(blank=True, max_length=255, verbose_name='PositionID')),
                ('Position', models.CharField(blank=True, max_length=255, verbose_name='Position')),
                ('IsForeigner', models.BooleanField(default=False, verbose_name='IsForeigner')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_companyofficer', to='stocks.Stock')),
            ],
            options={
                'verbose_name': 'CompanyOfficer',
                'verbose_name_plural': 'CompanyOfficers',
                'ordering': ('-created', '-id'),
            },
        ),
    ]
