# Generated by Django 3.0.2 on 2020-03-19 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_companyofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('TransactionID', models.CharField(blank=True, max_length=255, null=True, verbose_name='TransactionID')),
                ('MajorHolderID', models.CharField(blank=True, max_length=255, null=True, verbose_name='MajorHolderID')),
                ('IndividualHolderID', models.CharField(blank=True, max_length=255, null=True, verbose_name='IndividualHolderID')),
                ('InstitutionHolderID', models.CharField(blank=True, max_length=255, null=True, verbose_name='InstitutionHolderID')),
                ('InstitutionHolderSymbol', models.CharField(blank=True, max_length=255, null=True, verbose_name='InstitutionHolderSymbol')),
                ('InstitutionHolderExchange', models.CharField(blank=True, max_length=255, null=True, verbose_name='InstitutionHolderExchange')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('Position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('Symbol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Symbol')),
                ('Type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('ExecutionVolume', models.CharField(blank=True, max_length=255, null=True, verbose_name='ExecutionVolume')),
                ('ExecutionDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='ExecutionDate')),
                ('StartDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='StartDate')),
                ('EndDate', models.CharField(blank=True, max_length=255, null=True, verbose_name='EndDate')),
                ('RegisteredVolume', models.CharField(blank=True, max_length=255, null=True, verbose_name='RegisteredVolume')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_companytransaction', to='stocks.Stock')),
            ],
            options={
                'verbose_name': 'CompanyTransaction',
                'verbose_name_plural': 'CompanyTransactions',
                'ordering': ('-created', '-id'),
            },
        ),
    ]
