# Generated by Django 3.0.2 on 2020-03-21 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_companytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyFinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Year')),
                ('DilutedEPS', models.FloatField(blank=True, null=True, verbose_name='DilutedEPS')),
                ('BasicEPS', models.FloatField(blank=True, null=True, verbose_name='BasicEPS')),
                ('DilutedEPSGrowth', models.FloatField(blank=True, null=True, verbose_name='DilutedEPSGrowth')),
                ('BasicEPSGrowth', models.FloatField(blank=True, null=True, verbose_name='BasicEPSGrowth')),
                ('DilutedEPSGrowth_03Yr', models.FloatField(blank=True, null=True, verbose_name='DilutedEPSGrowth_03Yr')),
                ('BasicEPSGrowth_03Yr', models.FloatField(blank=True, null=True, verbose_name='BasicEPSGrowth_03Yr')),
                ('GrossMargin', models.FloatField(blank=True, null=True, verbose_name='GrossMargin')),
                ('EBITMargin', models.FloatField(blank=True, null=True, verbose_name='EBITMargin')),
                ('OperatingMargin', models.FloatField(blank=True, null=True, verbose_name='OperatingMargin')),
                ('ProfitMargin', models.FloatField(blank=True, null=True, verbose_name='ProfitMargin')),
                ('QuickRatio', models.FloatField(blank=True, null=True, verbose_name='QuickRatio')),
                ('CurrentRatio', models.FloatField(blank=True, null=True, verbose_name='CurrentRatio')),
                ('ROE', models.FloatField(blank=True, null=True, verbose_name='ROE')),
                ('ROA', models.FloatField(blank=True, null=True, verbose_name='ROA')),
                ('ROIC', models.FloatField(blank=True, null=True, verbose_name='ROIC')),
                ('CurrentAssetsTurnover', models.FloatField(blank=True, null=True, verbose_name='CurrentAssetsTurnover')),
                ('InventoryTurnover', models.FloatField(blank=True, null=True, verbose_name='InventoryTurnover')),
                ('ReceivablesTurnover', models.FloatField(blank=True, null=True, verbose_name='ReceivablesTurnover')),
                ('AssetsTurnover', models.FloatField(blank=True, null=True, verbose_name='AssetsTurnover')),
                ('SalesGrowth', models.FloatField(blank=True, null=True, verbose_name='SalesGrowth')),
                ('ProfitGrowth', models.FloatField(blank=True, null=True, verbose_name='ProfitGrowth')),
                ('Sales', models.FloatField(blank=True, null=True, verbose_name='Sales')),
                ('ProfitFromOperatingActivities', models.FloatField(blank=True, null=True, verbose_name='ProfitFromOperatingActivities')),
                ('ProfitFromFinancialActivities', models.FloatField(blank=True, null=True, verbose_name='ProfitFromFinancialActivities')),
                ('ProfitBeforeTax', models.FloatField(blank=True, null=True, verbose_name='ProfitBeforeTax')),
                ('ProfitAfterTax', models.FloatField(blank=True, null=True, verbose_name='ProfitAfterTax')),
                ('Cash', models.FloatField(blank=True, null=True, verbose_name='Cash')),
                ('LiquidAssets', models.FloatField(blank=True, null=True, verbose_name='LiquidAssets')),
                ('NetLiquidAssets', models.FloatField(blank=True, null=True, verbose_name='NetLiquidAssets')),
                ('TotalAssets', models.FloatField(blank=True, null=True, verbose_name='TotalAssets')),
                ('Equity', models.FloatField(blank=True, null=True, verbose_name='Equity')),
                ('TotalAssetsGrowth', models.FloatField(blank=True, null=True, verbose_name='TotalAssetsGrowth')),
                ('EBITMargin_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='EBITMargin_03YrAvg')),
                ('GrossMargin_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='GrossMargin_03YrAvg')),
                ('NetProfitMargin_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='NetProfitMargin_03YrAvg')),
                ('SalesGrowth_03Yr', models.FloatField(blank=True, null=True, verbose_name='SalesGrowth_03Yr')),
                ('OperatingMargin_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='OperatingMargin_03YrAvg')),
                ('PreTaxMargin_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='PreTaxMargin_03YrAvg')),
                ('ProfitGrowth_03Yr', models.FloatField(blank=True, null=True, verbose_name='ProfitGrowth_03Yr')),
                ('ROA_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='ROA_03YrAvg')),
                ('ROE_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='ROE_03YrAvg')),
                ('ROIC_03YrAvg', models.FloatField(blank=True, null=True, verbose_name='ROIC_03YrAvg')),
                ('EquityGrowth_03Yr', models.FloatField(blank=True, null=True, verbose_name='EquityGrowth_03Yr')),
                ('TotalAssetsGrowth_03Yr', models.FloatField(blank=True, null=True, verbose_name='TotalAssetsGrowth_03Yr')),
                ('LTDebtToEquity', models.FloatField(blank=True, null=True, verbose_name='LTDebtToEquity')),
                ('TotalDebtToEquity', models.FloatField(blank=True, null=True, verbose_name='TotalDebtToEquity')),
                ('BookValuePerShare', models.FloatField(blank=True, null=True, verbose_name='BookValuePerShare')),
                ('SalesPerShare', models.FloatField(blank=True, null=True, verbose_name='SalesPerShare')),
                ('TotalDebtToTotalAssets', models.FloatField(blank=True, null=True, verbose_name='TotalDebtToTotalAssets')),
                ('Liabilities', models.FloatField(blank=True, null=True, verbose_name='Liabilities')),
                ('CurrentLiabilities', models.FloatField(blank=True, null=True, verbose_name='CurrentLiabilities')),
                ('LongTermLiabilities', models.FloatField(blank=True, null=True, verbose_name='LongTermLiabilities')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_YearlyFinancialInfo', to='stocks.Stock')),
            ],
            options={
                'verbose_name': 'YearlyFinancialInfo',
                'verbose_name_plural': 'YearlyFinancialInfo',
                'ordering': ('-created', '-id'),
            },
        ),
    ]
