# Generated by Django 3.0.2 on 2020-03-21 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_yearlyfinancialinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyFinancialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Year', models.FloatField(blank=True, null=True, verbose_name='Year')),
                ('Quarter', models.FloatField(blank=True, null=True, verbose_name='Quarter')),
                ('BasicEPS_TTM', models.FloatField(blank=True, null=True, verbose_name='BasicEPS_TTM')),
                ('DilutedEPS_TTM', models.FloatField(blank=True, null=True, verbose_name='DilutedEPS_TTM')),
                ('SalesGrowth_MRQ', models.FloatField(blank=True, null=True, verbose_name='SalesGrowth_MRQ')),
                ('SalesGrowth_TTM', models.FloatField(blank=True, null=True, verbose_name='SalesGrowth_TTM')),
                ('ProfitGrowth_MRQ', models.FloatField(blank=True, null=True, verbose_name='ProfitGrowth_MRQ')),
                ('ProfitGrowth_TTM', models.FloatField(blank=True, null=True, verbose_name='ProfitGrowth_TTM')),
                ('BasicEPSGrowth_MRQ', models.FloatField(blank=True, null=True, verbose_name='BasicEPSGrowth_MRQ')),
                ('BasicEPSGrowth_TTM', models.FloatField(blank=True, null=True, verbose_name='BasicEPSGrowth_TTM')),
                ('DilutedEPSGrowth_MRQ', models.FloatField(blank=True, null=True, verbose_name='DilutedEPSGrowth_MRQ')),
                ('DilutedEPSGrowth_TTM', models.FloatField(blank=True, null=True, verbose_name='DilutedEPSGrowth_TTM')),
                ('QuickRatio_MRQ', models.FloatField(blank=True, null=True, verbose_name='QuickRatio_MRQ')),
                ('CurrentRatio_MRQ', models.FloatField(blank=True, null=True, verbose_name='CurrentRatio_MRQ')),
                ('LTDebtToEquity_MRQ', models.FloatField(blank=True, null=True, verbose_name='LTDebtToEquity_MRQ')),
                ('TotalDebtToEquity_MRQ', models.FloatField(blank=True, null=True, verbose_name='TotalDebtToEquity_MRQ')),
                ('TotalDebtToTotalAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='TotalDebtToTotalAssets_MRQ')),
                ('GrossMargin_TTM', models.FloatField(blank=True, null=True, verbose_name='GrossMargin_TTM')),
                ('EBITMargin_TTM', models.FloatField(blank=True, null=True, verbose_name='EBITMargin_TTM')),
                ('OperatingMargin_TTM', models.FloatField(blank=True, null=True, verbose_name='OperatingMargin_TTM')),
                ('PreTaxMargin_TTM', models.FloatField(blank=True, null=True, verbose_name='PreTaxMargin_TTM')),
                ('NetProfitMargin_TTM', models.FloatField(blank=True, null=True, verbose_name='NetProfitMargin_TTM')),
                ('ROA_TTM', models.FloatField(blank=True, null=True, verbose_name='ROA_TTM')),
                ('ROE_TTM', models.FloatField(blank=True, null=True, verbose_name='ROE_TTM')),
                ('ROIC_TTM', models.FloatField(blank=True, null=True, verbose_name='ROIC_TTM')),
                ('InventoryTurnover_TTM', models.FloatField(blank=True, null=True, verbose_name='InventoryTurnover_TTM')),
                ('ReceivablesTurnover_TTM', models.FloatField(blank=True, null=True, verbose_name='ReceivablesTurnover_TTM')),
                ('CurrentAssetsTurnover_TTM', models.FloatField(blank=True, null=True, verbose_name='CurrentAssetsTurnover_TTM')),
                ('AssetsTurnover_TTM', models.FloatField(blank=True, null=True, verbose_name='AssetsTurnover_TTM')),
                ('DividendGrowth_MRQ', models.FloatField(blank=True, null=True, verbose_name='DividendGrowth_MRQ')),
                ('DividendGrowth_TTM', models.FloatField(blank=True, null=True, verbose_name='DividendGrowth_TTM')),
                ('TotalAssetsGrowth_MRQ', models.FloatField(blank=True, null=True, verbose_name='TotalAssetsGrowth_MRQ')),
                ('TotalAssetsGrowth_TTM', models.FloatField(blank=True, null=True, verbose_name='TotalAssetsGrowth_TTM')),
                ('BookValuePerShare_MRQ', models.FloatField(blank=True, null=True, verbose_name='BookValuePerShare_MRQ')),
                ('SalesPerShare_TTM', models.FloatField(blank=True, null=True, verbose_name='SalesPerShare_TTM')),
                ('BasicEPS_MRQ', models.FloatField(blank=True, null=True, verbose_name='BasicEPS_MRQ')),
                ('DilutedEPS_MRQ', models.FloatField(blank=True, null=True, verbose_name='DilutedEPS_MRQ')),
                ('NetSales_MRQ', models.FloatField(blank=True, null=True, verbose_name='NetSales_MRQ')),
                ('Dividend_MRQ', models.FloatField(blank=True, null=True, verbose_name='Dividend_MRQ')),
                ('TotalAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='TotalAssets_MRQ')),
                ('CurrentAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='CurrentAssets_MRQ')),
                ('Inventories_MRQ', models.FloatField(blank=True, null=True, verbose_name='Inventories_MRQ')),
                ('ProfitAfterTax_MRQ', models.FloatField(blank=True, null=True, verbose_name='ProfitAfterTax_MRQ')),
                ('SharesOutstanding_MRQ', models.FloatField(blank=True, null=True, verbose_name='SharesOutstanding_MRQ')),
                ('Cash_MRQ', models.FloatField(blank=True, null=True, verbose_name='Cash_MRQ')),
                ('NetLiquidAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='NetLiquidAssets_MRQ')),
                ('CurrentLiabilities_MRQ', models.FloatField(blank=True, null=True, verbose_name='CurrentLiabilities_MRQ')),
                ('LongTermLiabilities_MRQ', models.FloatField(blank=True, null=True, verbose_name='LongTermLiabilities_MRQ')),
                ('Liabilities_MRQ', models.FloatField(blank=True, null=True, verbose_name='Liabilities_MRQ')),
                ('Equity_MRQ', models.FloatField(blank=True, null=True, verbose_name='Equity_MRQ')),
                ('ProfitBeforeTax_MRQ', models.FloatField(blank=True, null=True, verbose_name='ProfitBeforeTax_MRQ')),
                ('FixedAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='FixedAssets_MRQ')),
                ('LiquidAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='LiquidAssets_MRQ')),
                ('IntangibleAssets_MRQ', models.FloatField(blank=True, null=True, verbose_name='IntangibleAssets_MRQ')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_QuarterlyFinancialInfo', to='stocks.Stock')),
            ],
            options={
                'verbose_name': 'QuarterlyFinancialInfo',
                'verbose_name_plural': 'QuarterlyFinancialInfo',
                'ordering': ('-created', '-id'),
            },
        ),
    ]
