# Generated by Django 3.0.2 on 2020-03-22 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_quarterlyfinancialinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastestFinancialReportsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Type', models.CharField(choices=[('2', '2'), ('1', '1'), ('3', '3'), ('4', '4')], default='2', max_length=1, verbose_name='Type')),
                ('ID', models.FloatField(blank=True, null=True, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('ParentID', models.FloatField(blank=True, null=True, verbose_name='ParentID')),
                ('Expanded', models.BooleanField(default=False, verbose_name='Expanded')),
                ('Level', models.FloatField(blank=True, null=True, verbose_name='Level')),
                ('Field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LastestFinancialReportsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Period')),
                ('Year', models.FloatField(blank=True, null=True, verbose_name='Year')),
                ('Quarter', models.FloatField(blank=True, null=True, verbose_name='Quarter')),
                ('Value', models.FloatField(blank=True, null=True, verbose_name='Value')),
                ('Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='LastestFinancialReportsValue_Name', to='stocks.LastestFinancialReportsName')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='LastestFinancialReportsValue_Stock', to='stocks.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
