# Generated by Django 3.0.2 on 2020-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_lastestfinancialreportsname_lastestfinancialreportsvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastestfinancialreportsvalue',
            name='Name',
        ),
        migrations.AddField(
            model_name='lastestfinancialreportsvalue',
            name='ID',
            field=models.FloatField(blank=True, null=True, verbose_name='ID'),
        ),
    ]
