# Generated by Django 3.0.2 on 2020-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_lastestfinancialreportsvalue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestfinancialreportsname',
            name='IndustryType',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='IndustryType'),
        ),
    ]
