# Generated by Django 3.0.2 on 2020-03-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_companyhistoricalquote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyhistoricalquote',
            unique_together={('Stock', 'Date')},
        ),
    ]
