# Generated by Django 3.0.2 on 2020-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_auto_20200328_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='IsFavorite',
            field=models.BooleanField(default=False, verbose_name='IsFavorite'),
        ),
        migrations.AddField(
            model_name='stock',
            name='IsVN30',
            field=models.BooleanField(default=False, verbose_name='IsVN30'),
        ),
    ]
