# Generated by Django 3.0.2 on 2020-05-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_auto_20200526_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Symbol',
        ),
        migrations.AddField(
            model_name='company',
            name='Stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_company', to='stocks.Stock'),
        ),
    ]
