# Generated by Django 3.0.2 on 2020-06-01 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_auto_20200527_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisiveIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('LowestPoint', models.FloatField(blank=True, null=True, verbose_name='LowestPoint')),
                ('SellPoint', models.FloatField(blank=True, null=True, verbose_name='SellPoint')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_decisive_index', to='stocks.Stock')),
            ],
            options={
                'verbose_name': 'DecisiveIndex',
                'verbose_name_plural': 'DecisiveIndexes',
                'ordering': ('-created', '-id'),
            },
        ),
    ]
