# Generated by Django 3.0.2 on 2020-06-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_decisiveindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestfinancialinfo',
            name='Symbol',
        ),
        migrations.AddField(
            model_name='latestfinancialinfo',
            name='Stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_lastestFinancialInfo', to='stocks.Stock'),
        ),
    ]
