# Generated by Django 3.0.2 on 2020-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_auto_20200604_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='IsBlackList',
            field=models.BooleanField(default=False, verbose_name='IsBlackList'),
        ),
    ]
