# Generated by Django 3.0.2 on 2020-07-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_stock_isblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
