# Generated by Django 3.0.2 on 2020-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_stock_isstrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='IsStrong',
            field=models.BooleanField(default=True, verbose_name='IsStrong'),
        ),
    ]
