# Generated by Django 3.0.2 on 2020-09-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_auto_20200916_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='IsStrong',
        ),
    ]
