# Generated by Django 3.0.2 on 2020-09-28 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_stock_isonstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('TodayCapital', models.FloatField(blank=True, null=True, verbose_name='TodayCapital')),
                ('PercentChange', models.FloatField(blank=True, null=True, verbose_name='PercentChange')),
                ('MarketCap', models.FloatField(blank=True, null=True, verbose_name='MarketCap')),
                ('DealVolume', models.FloatField(blank=True, null=True, verbose_name='DealVolume')),
                ('Stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_latest', to='stocks.Stock')),
            ],
            options={
                'verbose_name': 'Latest',
                'verbose_name_plural': 'Latest',
                'ordering': ('-created', '-id'),
            },
        ),
    ]
