# Generated by Django 3.0.2 on 2020-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='AverageVolume30',
            field=models.FloatField(blank=True, null=True, verbose_name='AverageVolume30'),
        ),
    ]
