# Generated by Django 3.0.2 on 2020-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_latest_averagevolume30'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='PercentChange',
        ),
        migrations.AddField(
            model_name='latest',
            name='PriceChange',
            field=models.FloatField(blank=True, null=True, verbose_name='PriceChange'),
        ),
    ]
