# Generated by Django 3.1.3 on 2020-12-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0035_auto_20201008_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiveindex',
            name='LastBuyPoint',
            field=models.FloatField(blank=True, null=True, verbose_name='LastBuyPoint'),
        ),
    ]
